### ISSUE TITLE
2 deprecations reported by Atom

### ISSUE THREAD

**Issue by sethladd** [austincummings/atom-dart#5]
Just installed this plugin, and Atom reported:

![screen shot 2015-05-11 at 4 18 30 pm](https://cloud.githubusercontent.com/assets/5479/7577098/6b3b1dd2-f7f9-11e4-8c58-223963877b98.png)

**Comment by austincummings** [comment]
Fixed by a4c7012d753d7fe8bc1ce1c6fd67f19487030beb and 8d05eb808b5c88a79723ba32b1e1b0bc7ed49511

**Comment by sethladd** [comment]
Thanks!
